"""Add updated_vacancies field

Revision ID: 3a9cd210fbcc
Revises: c6b0c9facf91
Create Date: 2026-01-31 23:12:28.096455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a9cd210fbcc'
down_revision: Union[str, Sequence[str], None] = 'c6b0c9facf91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
