"""Add original_vacancy_id in favorite_vacancies table

Revision ID: 490dc4d26417
Revises: 15dffeaa3696
Create Date: 2026-02-04 21:05:32.863062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '490dc4d26417'
down_revision: Union[str, Sequence[str], None] = '15dffeaa3696'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite_vacancies', sa.Column('original_vacancy_id', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorite_vacancies', 'original_vacancy_id')
    # ### end Alembic commands ###
