"""Add parsing_jobs table

Revision ID: c6b0c9facf91
Revises: 5972eaa35cb5
Create Date: 2026-01-30 16:14:13.286103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6b0c9facf91'
down_revision: Union[str, Sequence[str], None] = '5972eaa35cb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parsing_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('added_vacancies', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCESS', 'ERROR', name='parsestatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parsing_jobs_id'), 'parsing_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_parsing_jobs_started_at'), 'parsing_jobs', ['started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parsing_jobs_started_at'), table_name='parsing_jobs')
    op.drop_index(op.f('ix_parsing_jobs_id'), table_name='parsing_jobs')
    op.drop_table('parsing_jobs')
    # ### end Alembic commands ###
